# Generated by Django 5.2 on 2025-05-07 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("level_completed", models.CharField(max_length=100)),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("result_type", models.CharField(max_length=50)),
                ("result_value", models.CharField(max_length=20)),
                ("completion_year", models.IntegerField()),
                ("start_year", models.IntegerField()),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "academic_background",
                "ordering": ["-completion_year"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_term", models.CharField(max_length=50)),
                ("personal_statement", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("posted_date", models.DateField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("tags", models.CharField(blank=True, max_length=500, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "blog",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField()),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blog_comments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "degree",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "field",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FinancialAidAndScholarships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aid_name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("type_and_for_whom", models.TextField(blank=True, null=True)),
                ("eligibility", models.TextField(blank=True, null=True)),
                ("renewal_criteria", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "financial_aid_and_scholarships",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfessionalScopes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profession", models.CharField(max_length=100)),
                ("more_depth_in_profession", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "professional_scopes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("program_overview", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "program",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField()),
                ("posted_date", models.DateField()),
            ],
            options={
                "db_table": "program_reviews",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavedItems",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("uni", "University"), ("prog", "Program")],
                        max_length=4,
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("saved_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "saved_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavedProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "saved_program",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavedUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "saved_universities",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("two_line_info", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "world_university_ranking",
                    models.IntegerField(blank=True, null=True),
                ),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "university",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("Public", "Public"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "university_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserDocuments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("diploma", "Diploma"),
                            ("transcript", "Academic Transcript"),
                            ("resume", "Resume"),
                            ("passport", "Passport"),
                            ("standardized_test", "Standardized Test Results"),
                            ("language_test", "Language Test Results"),
                            ("recommendation", "Letter of Recommendation"),
                            ("eca", "Educational Credential Assessment"),
                            ("other", "Other Documents"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.TextField()),
                ("original_filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramContact",
            fields=[
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.program",
                    ),
                ),
                (
                    "program_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "program_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("program_website", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "program_contact",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramRequirements",
            fields=[
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.program",
                    ),
                ),
                (
                    "tuition",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "taught_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("test_score_SAT", models.IntegerField(blank=True, null=True)),
                ("test_score_TOEFL", models.IntegerField(blank=True, null=True)),
                (
                    "test_score_IELTS",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("additional_req", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "program_requirements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramSchedule",
            fields=[
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.program",
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("credits", models.IntegerField(blank=True, null=True)),
                (
                    "start_semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fall", "Fall"),
                            ("Summer", "Summer"),
                            ("Winter", "Winter"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("application_opens_date", models.DateField(blank=True, null=True)),
                ("early_decision", models.DateField(blank=True, null=True)),
                ("regular_decision", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("result_publish", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "program_schedule",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityContact",
            fields=[
                (
                    "university",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.university",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("uni_website", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "university_contact",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityDescription",
            fields=[
                (
                    "university",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.university",
                    ),
                ),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "housing_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dining_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_org_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "athletics_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "university_description",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityStats",
            fields=[
                (
                    "university",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="portal.university",
                    ),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("total_reviews", models.IntegerField(blank=True, null=True)),
                ("total_students", models.IntegerField(blank=True, null=True)),
                ("total_country_students", models.IntegerField(blank=True, null=True)),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "student_faculty_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_tuition",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_cost_of_living",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "university_stats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("application", "Application Update"),
                            ("system", "System Notification"),
                            ("message", "New Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
