# Generated by Django 5.2 on 2025-05-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="BlogComment",
        ),
    ]
