# Generated by Django 5.2 on 2025-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_delete_blog_delete_blogcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "review_votes",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="programreviews",
            options={"managed": False, "ordering": ["-posted_date"]},
        ),
    ]
