# Generated by Django 5.2 on 2025-05-07 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university_portal", "0005_alter_userprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="academicbackground",
            name="completion_year_after_start_year",
        ),
        migrations.RemoveConstraint(
            model_name="saveditem",
            name="unique_saved_item",
        ),
        migrations.RemoveIndex(
            model_name="academicbackground",
            name="academic_ba_user_id_5bfc26_idx",
        ),
        migrations.RemoveIndex(
            model_name="academicbackground",
            name="academic_ba_field_o_273a8f_idx",
        ),
        migrations.RemoveIndex(
            model_name="saveditem",
            name="saved_items_user_id_9dc278_idx",
        ),
        migrations.RemoveIndex(
            model_name="userdocument",
            name="user_docume_user_id_16802b_idx",
        ),
        migrations.RemoveIndex(
            model_name="userdocument",
            name="user_docume_documen_ab9b15_idx",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="completion_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="start_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="saveditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saveditem",
            unique_together={("user", "item_type", "item_id")},
        ),
    ]
